### ISSUE TITLE
Peer lost connection error.

### ISSUE THREAD

**Issue by aparijat** [spreedbox/spreedbox#10]
I changed the HTTP and HTTPS ports and port forwarded them on my router. I tried to use dynamic DNS to access spreedbox. I am able to call in and briefly connect but then the call ends within a few seconds with the error "Peer lost connection. Check configuration".

**Comment by longsleep** [comment]
Hi,

most likely the Peer connection cannot be established because of firewalls between the peers.  The Spreedbox uses a STUN server by default, and thus supports firewall trespassing if the firewalls allow it. In restrictive firewalled environments, a TURN server is required (on a publicly available IP address, reachable directly by both peers). See https://github.com/strukturag/spreed-webrtc#running-for-production for hints and references to an open source TURN server software.

Best regards
Simon

**Comment by longsleep** [comment]
Closing as no further feedback. In the meantime, we also have added TURN setup instructions to the Wiki. See https://github.com/spreedbox/spreedbox/wiki/Use-TURN-server
